"""
Terminal Dashboard — Beautiful portfolio visualization in the terminal.
Uses rich-style formatting with colors, tables, and charts.
"""

import math
from typing import Optional

from fidelity_nurture.core.portfolio import Portfolio
from fidelity_nurture.core.analyzer import PortfolioAnalyzer, HealthScore
from fidelity_nurture.ai.predictor import RiskPredictor, RiskAssessment
from fidelity_nurture.ai.optimizer import PortfolioOptimizer, OptimizationResult


# ANSI color codes
class C:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    GREEN = "\033[92m"
    RED = "\033[91m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    MAGENTA = "\033[95m"
    CYAN = "\033[96m"
    WHITE = "\033[97m"
    BG_GREEN = "\033[42m"
    BG_RED = "\033[41m"
    BG_YELLOW = "\033[43m"
    BG_BLUE = "\033[44m"


def colored(value: float, prefix: str = "$", show_sign: bool = True) -> str:
    """Format a number with color (green for positive, red for negative)."""
    if value > 0:
        sign = "+" if show_sign else ""
        return f"{C.GREEN}{sign}{prefix}{value:,.2f}{C.RESET}"
    elif value < 0:
        return f"{C.RED}{prefix}{value:,.2f}{C.RESET}"
    return f"{C.WHITE}{prefix}{value:,.2f}{C.RESET}"


def colored_pct(value: float) -> str:
    """Format percentage with color."""
    if value > 0:
        return f"{C.GREEN}+{value:.2f}%{C.RESET}"
    elif value < 0:
        return f"{C.RED}{value:.2f}%{C.RESET}"
    return f"{C.WHITE}{value:.2f}%{C.RESET}"


def bar_chart(items: list[tuple[str, float]], max_width: int = 30) -> str:
    """Create a horizontal bar chart in the terminal."""
    if not items:
        return ""

    max_val = max(abs(v) for _, v in items) if items else 1
    lines = []
    for label, value in items:
        bar_len = int((abs(value) / max_val) * max_width) if max_val > 0 else 0
        if value >= 0:
            bar = f"{C.GREEN}{'█' * bar_len}{'░' * (max_width - bar_len)}{C.RESET}"
        else:
            bar = f"{C.RED}{'█' * bar_len}{'░' * (max_width - bar_len)}{C.RESET}"
        lines.append(f"  {label:>12s} {bar} {colored_pct(value)}")
    return "\n".join(lines)


def grade_color(grade: str) -> str:
    """Get color for a health grade."""
    if grade.startswith("A"):
        return C.GREEN
    elif grade.startswith("B"):
        return C.CYAN
    elif grade.startswith("C"):
        return C.YELLOW
    else:
        return C.RED


def risk_color(level: str) -> str:
    """Get color for risk level."""
    return {
        "LOW": C.GREEN,
        "MODERATE": C.YELLOW,
        "HIGH": C.RED,
        "CRITICAL": f"{C.BG_RED}{C.WHITE}",
    }.get(level, C.WHITE)


class Dashboard:
    """
    Terminal dashboard for portfolio visualization.
    
    Renders portfolio overview, health scores, risk assessment,
    and optimization suggestions in a clean terminal format.
    """

    def __init__(self, portfolio: Portfolio):
        self.portfolio = portfolio
        self.analyzer = PortfolioAnalyzer(portfolio)
        self.predictor = RiskPredictor(portfolio)
        self.optimizer = PortfolioOptimizer(portfolio)

    def render(self) -> str:
        """Render complete dashboard."""
        sections = [
            self._header(),
            self._portfolio_overview(),
            self._holdings_table(),
            self._sector_chart(),
            self._health_score(),
            self._risk_assessment(),
            self._anomalies(),
            self._optimization(),
            self._footer(),
        ]
        return "\n\n".join(sections)

    def _header(self) -> str:
        return (
            f"\n{C.BOLD}{C.CYAN}{'═' * 70}{C.RESET}\n"
            f"{C.BOLD}{C.CYAN}  💰 NurtureFolio — AI Portfolio Intelligence{C.RESET}\n"
            f"{C.DIM}  Portfolio: {self.portfolio.name} | "
            f"Generated by Chandan's AI{C.RESET}\n"
            f"{C.BOLD}{C.CYAN}{'═' * 70}{C.RESET}"
        )

    def _portfolio_overview(self) -> str:
        s = self.portfolio.summary()
        pnl_color = C.GREEN if s["total_pnl"] >= 0 else C.RED
        return (
            f"{C.BOLD}📊 PORTFOLIO OVERVIEW{C.RESET}\n"
            f"  ┌─────────────────────────────────────────┐\n"
            f"  │  Total Value:   {C.BOLD}{C.WHITE}${s['total_value']:>14,.2f}{C.RESET}     │\n"
            f"  │  Cost Basis:    ${s['total_cost']:>14,.2f}     │\n"
            f"  │  Unrealized P&L:{colored(s['total_pnl']):>20s}     │\n"
            f"  │  Return:        {colored_pct(s['total_pnl_pct']):>20s}     │\n"
            f"  │  Holdings:      {C.WHITE}{s['num_holdings']:>14d}{C.RESET}     │\n"
            f"  │  Cash:          ${s['cash_balance']:>14,.2f}     │\n"
            f"  └─────────────────────────────────────────┘"
        )

    def _holdings_table(self) -> str:
        lines = [f"{C.BOLD}📋 HOLDINGS{C.RESET}"]
        lines.append(f"  {'Symbol':<8s} {'Name':<22s} {'Value':>12s} {'P&L':>10s} {'Weight':>8s}")
        lines.append(f"  {'─' * 62}")

        weights = self.portfolio.get_weights()
        for h in sorted(self.portfolio.holdings, key=lambda x: x.market_value, reverse=True):
            w = weights.get(h.symbol, 0)
            pnl_str = colored_pct(h.unrealized_pnl_pct)
            name = h.name[:20] + ".." if len(h.name) > 20 else h.name
            lines.append(
                f"  {C.BOLD}{h.symbol:<8s}{C.RESET} {name:<22s} "
                f"${h.market_value:>10,.2f} {pnl_str:>20s} {C.DIM}{w:>6.1f}%{C.RESET}"
            )

        return "\n".join(lines)

    def _sector_chart(self) -> str:
        alloc = self.portfolio.get_sector_allocation()
        items = sorted(alloc.items(), key=lambda x: x[1], reverse=True)
        chart = bar_chart(items)
        return f"{C.BOLD}🏢 SECTOR ALLOCATION{C.RESET}\n{chart}"

    def _health_score(self) -> str:
        score = self.analyzer.analyze()
        gc = grade_color(score.grade)

        return (
            f"{C.BOLD}🏥 PORTFOLIO HEALTH{C.RESET}\n"
            f"  ┌─────────────────────────────────────────┐\n"
            f"  │  Overall:        {gc}{C.BOLD}{score.grade:>4s}{C.RESET} ({score.overall:.0f}/100)       │\n"
            f"  │  Diversification:{self._score_bar(score.diversification)}       │\n"
            f"  │  Risk Mgmt:     {self._score_bar(score.risk)}       │\n"
            f"  │  Performance:   {self._score_bar(score.performance)}       │\n"
            f"  │  Concentration: {self._score_bar(score.concentration)}       │\n"
            f"  └─────────────────────────────────────────┘"
        )

    def _score_bar(self, score: float) -> str:
        filled = int(score / 10)
        empty = 10 - filled
        if score >= 70:
            color = C.GREEN
        elif score >= 50:
            color = C.YELLOW
        else:
            color = C.RED
        return f"{color}{'█' * filled}{C.DIM}{'░' * empty}{C.RESET} {score:.0f}"

    def _risk_assessment(self) -> str:
        risk = self.predictor.assess_risk()
        rc = risk_color(risk.risk_level)

        lines = [
            f"{C.BOLD}⚠️  RISK ASSESSMENT{C.RESET}",
            f"  Risk Level:    {rc}{C.BOLD} {risk.risk_level} {C.RESET} ({risk.risk_score:.0f}/100)",
            f"  Volatility:    {risk.volatility_estimate:.1f}% annualized",
            f"  Max Drawdown:  {risk.max_drawdown_estimate:.1f}% estimated",
            f"  Sharpe Ratio:  {risk.sharpe_estimate:.2f}",
            f"  Portfolio Beta: {risk.beta_estimate:.2f}",
        ]

        if risk.risk_factors:
            lines.append(f"\n  {C.YELLOW}Risk Factors:{C.RESET}")
            for factor in risk.risk_factors:
                lines.append(f"    • {factor}")

        return "\n".join(lines)

    def _anomalies(self) -> str:
        anomalies = self.predictor.detect_anomalies()
        if not anomalies:
            return f"{C.BOLD}✅ ANOMALIES{C.RESET}\n  {C.GREEN}No anomalies detected — portfolio looks healthy!{C.RESET}"

        lines = [f"{C.BOLD}🔍 ANOMALIES DETECTED{C.RESET}"]
        for a in anomalies:
            icon = {"INFO": "ℹ️", "WARNING": "⚠️", "CRITICAL": "🚨"}.get(a.severity, "•")
            sc = {"INFO": C.BLUE, "WARNING": C.YELLOW, "CRITICAL": C.RED}.get(a.severity, C.WHITE)
            lines.append(f"  {icon} {sc}[{a.severity}]{C.RESET} {a.description}")
            lines.append(f"    → {C.DIM}{a.recommendation}{C.RESET}")

        return "\n".join(lines)

    def _optimization(self) -> str:
        opt = self.optimizer.optimize(strategy="maximize_sharpe", risk_tolerance="moderate")

        lines = [
            f"{C.BOLD}🎯 OPTIMIZATION SUGGESTIONS{C.RESET}",
            f"  Strategy: {C.CYAN}{opt.strategy}{C.RESET}",
            f"  Expected Return: {colored_pct(opt.expected_return)}",
            f"  Expected Risk:   {opt.expected_risk:.1f}%",
            f"  Sharpe Ratio:    {opt.sharpe_ratio:.2f}",
            f"\n  {C.DIM}{opt.rationale}{C.RESET}",
        ]

        if opt.changes:
            lines.append(f"\n  {C.BOLD}Suggested Changes:{C.RESET}")
            for c in opt.changes[:5]:
                action_color = C.GREEN if c["action"] == "BUY" else C.RED
                lines.append(
                    f"    {action_color}{c['action']:>5s}{C.RESET} {c['symbol']:<8s} "
                    f"{c['current_weight']:.1f}% → {c['target_weight']:.1f}% "
                    f"(${c['amount']:,.0f})"
                )

        return "\n".join(lines)

    def _footer(self) -> str:
        return (
            f"{C.DIM}{'─' * 70}{C.RESET}\n"
            f"{C.DIM}  Built with 🍬 by Sweety | NurtureFolio v1.0.0{C.RESET}\n"
            f"{C.DIM}  github.com/Chandan-14r/FidelityNurture{C.RESET}"
        )
